name: test + build-release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  get-apk:
    name: Get APK
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v1
      with: { java-version: 11 }
    - uses: android-actions/setup-android@v2

    - name: Run tests
      run: |
        chmod +x ./gradlew
        ./gradlew --no-daemon test

    - name: Build release APK
      if: success()
      run: |
        ./gradlew --no-daemon assembleCicd

    - name: Clearing
      if: success()
      run: |
        for filename in app/build/outputs/apk/cicd/*.apk; do mv "./$filename" "./$(echo "$filename" | sed -e 's/-unsigned//g')";  done

    - name: Sign APK
      if: success()
      uses: r0adkll/sign-android-release@v1
      id: sign_app
      with:
        releaseDirectory: app/build/outputs/apk/cicd
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.SIGNING_KEY_ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}
      env:
        BUILD_TOOL_VERSION: "30.0.2"

    - name: Upload APK
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: app-release
        path: app/build/outputs/apk/cicd/*-signed.apk
        retention-days: 1

  send-apk:
    needs: get-apk
    name: Send Telegram Notification
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Get artifact
      uses: actions/download-artifact@master
      with:
        name: app-release
        path: app/build/outputs/apk

    - name: Get current time
      if: ${{ always() }}
      uses: josStorer/get-current-time@v2
      id: current_time
      with:
        format: DD.MM.YYYY kk:mm:ssZZ
        utcOffset: "+03:00"

    - name: Telegram Notify
      if: ${{ always() }}
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        format: html
        message: |
          <b>${{ steps.current_time.outputs.formattedTime }}</b>

          Repository: ${{ github.repository }}
          Build was initiated by <b>${{ github.actor }}</b> with <b>${{ github.event_name }}</b>
          Build status: <b>${{ job.status }}</b>
        document: app/build/outputs/apk/*-signed.apk
